In [1]:
import numpy as np
from numpy import linalg as LA

## NumPy Matrices


Matrices can be created by making a 2D numpy array or using built-in functions.
- `np.ones(n)`: creates an nxn matrix of all ones
- `np.eye(n)`: creates an nxn identity matrix
- `A = np.array([ [1,2],[3,4] ])`: creates a 'matrix' 

Documentation for NumPy array creation routines: https://numpy.org/doc/stable/reference/routines.array-creation.html

**Exercise:** Run the following code. What do you notice about $A$ and $B$?


In [3]:
A = np.ones(5) + np.eye(5)
print("A=",A)

I = np.eye(5)
B = A*I

print("B=",B)

[1. 1. 1. 1. 1.]
A= [[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]
B= [[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]


Many matrix-vector operations act like linear algebra, but some do not. In the following code, what do you expect C1 and C2 to be?

In [8]:
# Create an array v of length 5
v = np.array([1,2,3,4,5])

# Multiply A and v
C1 = A*v
C2 = A + v



**Matrix multiplication** can be done using the `@` operator. i.e., `M = A*B` for appropriately sized np arrays $A$ and $B$.

In [10]:
# Try matrix multiplication!

## Linear Algebra Routines

`numpy.linalg` gives helpful linear algebra routines. For example:
- `LA.norm(A,2)`: $\ell_2$ matrix/vector norm https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
- `LA.norm(A,np.inf)`: $\ell_{\infty}$ matrix/vector norm 
- `w,v = LA.eig(A)`: eigenvalues (w) and eigenvectors (v) of the matrix https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html


Additional helpful commands:
- `np.transpose(A)`: transpose of matrix A
- `np.diag(A)`: Extracts the diagonal of the matrix A (See other uses here https://numpy.org/doc/stable/reference/generated/numpy.diag.html)


More information and routines can be found on the documentation: https://numpy.org/doc/stable/reference/routines.linalg.html

**Exercise:** Find the eigenvalues and $\ell_2$-norm of the following matrices. Check that 
$$
\|A\|_2 = \left[\rho\left( A^t A\right)\right]^{1/2}.
$$

In [22]:
A1 = np.array([[2,1,0],
             [1,2,0],
             [0,0,3]])

l2_norm = LA.norm(A1, 2)

assert np.isclose(l2_norm, np.max((LA.eigvals(A1.T@A1))**0.5, axis=0))

In [23]:
A2 = np.array([[-1,2,0],
             [0,3,4],
             [0,0,7]])

l2_norm = LA.norm(A2, 2)

assert np.isclose(l2_norm, np.max((LA.eigvals(A2.T@A2))**0.5, axis=0))

## Convergent Matrices

**Definition:** A matrix $A \in \mathbb{R}^{n\times n}$ is said to be _convergent_ if 
$$
\lim_{k \rightarrow \infty} \left( A^k\right)_{i,j} = 0 \qquad \forall \ i,j = 1, \dots, n.
$$

**Exercise:** Check if the following matrices are convergent by (1) multiplying the matrices many times, and (2) computing the spectral radius.
$$
A = \begin{pmatrix} \frac{1}{2} & 0 \\ 16 & \frac{1}{2} \end{pmatrix}, \qquad B = \begin{pmatrix} 1 & 0 \\ \frac{1}{4} & \frac{1}{2} \end{pmatrix}. 
$$

In [35]:
A = np.array([[0.5, 0], [16, 0.5]])

print(np.round(LA.matrix_power(A, 100), 3))

[[0. 0.]
 [0. 0.]]


In [36]:
B = np.array([[1, 0], [0.25, 0.5]])

print(np.round(LA.matrix_power(B, 100), 3))

[[1.  0. ]
 [0.5 0. ]]
